// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau3GvmGc7rqHWs1WZqg1JzgKTeaRcDEU',
    appId: '1:555247274556:web:35d03c4512cf5f426c9139',
    messagingSenderId: '555247274556',
    projectId: 'simple-dc013',
    authDomain: 'simple-dc013.firebaseapp.com',
    storageBucket: 'simple-dc013.appspot.com',
    measurementId: 'G-QZ1VRX0Q4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv2z1PgcEgEZnak6bQS-OaQP215lUQOF4',
    appId: '1:555247274556:android:cd4f67572ca7e3a96c9139',
    messagingSenderId: '555247274556',
    projectId: 'simple-dc013',
    storageBucket: 'simple-dc013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGWZRbBHckHLrfvJkXrnuH9AUlDaNgR8',
    appId: '1:555247274556:ios:219e6426f6b879876c9139',
    messagingSenderId: '555247274556',
    projectId: 'simple-dc013',
    storageBucket: 'simple-dc013.appspot.com',
    iosClientId: '555247274556-h57d3e832mloka6o9jquug759o1o2d1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.notfication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGWZRbBHckHLrfvJkXrnuH9AUlDaNgR8',
    appId: '1:555247274556:ios:219e6426f6b879876c9139',
    messagingSenderId: '555247274556',
    projectId: 'simple-dc013',
    storageBucket: 'simple-dc013.appspot.com',
    iosClientId: '555247274556-h57d3e832mloka6o9jquug759o1o2d1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.notfication',
  );
}
